
# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: G-7NBSBNJPXW

menu:
- {name: 'Posts'     , url: 'posts.html'    }
- {name: 'System'    , url: 'my-system.html'}
- {name: 'Library'   , url: 'my-library.html'}
- {name: 'About'     , url: 'about.html'    }


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/mohamedrezk122'}
- {icon: 'twitter',    link: 'https://twitter.com/rezk1222'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/mohamed-m-rezk/'}
- {icon: 'facebook',   link: 'https://www.facebook.com/mohrizq895/'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: ''
